### ISSUE TITLE
Sinks: sink with OTEL status validation is wrong (stays active when it shouldn't be)

### ISSUE THREAD

**Issue by manrodrigues** [orb-community/orb#2021]
I'm opening only one ticket, because maybe the same action can solve the problems.. If we need separated actions, we could split it in multiple tasks on future. 

We have a problem with sink status validation. It stays active when it shouldn't be:
1) when the sink doesn't have an otel flag and the agents do
2) when it has invalid settings already at creation
3) when there are invalid credentials after editing

This can mean either that the validation is wrong, or that some data is being passed on the wrong place.. we need to confirm.. because grafana runs out of data, but no error is indicated.. and because this is our "confidence" that data is arriving in the correct place.

**Comment by lpegoraro** [comment]
We might need to create the Central Notification System before this

Possible tasks
- [ ] Expose Healthcheck and logs of Otel-Collectors
- [ ] Sinker-Otel listen to each otel-collectors metrics, and push to sinker event

**Comment by lpegoraro** [comment]
# TODOs

- [ ] Use @etaques otel-collector image
- [ ] Make Maestro look into each collector healthcheck once every x minutes (default 5) and check logs for errors
- [ ] Make Maestro publish changes on sinks redis hashtable
